<a href="https://colab.research.google.com/github/mariya347/MachineLearning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torchvision.transforms as transforms
print(torch.__version__)

2.2.1+cu121


In [ ]:
#A scalar is a single number and in tensor-speak it's a zero dimension tensor.
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#how many dimensions the array have.
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vectors are represented as 1-dimensional tensors
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
#matrix has 2-dimensions
MATRIX = torch.tensor([[1,2,3], [4,5,6], [1,2,3]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
MATRIX[1]

tensor([4, 5, 6])

In [ ]:
TENSOR = torch.tensor([ [[1, 2, 3,7],
                         [3, 6, 9,7],
                         [2, 4, 5,7]
                        ],
                        [
                         [1, 2, 3,7],
                         [3, 6, 9,7],
                         [2, 4, 5,7]
                        ]
                        ]
                      )
TENSOR

tensor([[[1, 2, 3, 7],
         [3, 6, 9, 7],
         [2, 4, 5, 7]],

        [[1, 2, 3, 7],
         [3, 6, 9, 7],
         [2, 4, 5, 7]]])

In [ ]:
#square brackets
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 4])

In [ ]:
TENSOR[0,1,1]

tensor(6)

In [ ]:
rand_tensor = torch.rand(size=(3,3,3))
rand_tensor

tensor([[[0.2180, 0.9247, 0.3049],
         [0.3447, 0.9092, 0.0301],
         [0.4883, 0.2844, 0.3311]],

        [[0.5781, 0.5061, 0.1666],
         [0.5875, 0.5372, 0.2665],
         [0.5193, 0.0236, 0.1634]],

        [[0.7207, 0.0161, 0.2187],
         [0.8478, 0.7070, 0.5898],
         [0.1243, 0.4607, 0.7279]]])

In [ ]:
#[height, width, color_channels]
image = torch.rand(size = (244,244,3))
image

tensor([[[0.8992, 0.9879, 0.7302],
         [0.0597, 0.6000, 0.1084],
         [0.3518, 0.8344, 0.0742],
         ...,
         [0.1704, 0.0345, 0.4006],
         [0.4061, 0.7127, 0.2022],
         [0.5772, 0.7490, 0.9854]],

        [[0.6634, 0.5388, 0.6474],
         [0.5606, 0.0428, 0.4736],
         [0.3653, 0.8213, 0.3451],
         ...,
         [0.9837, 0.5293, 0.3006],
         [0.4621, 0.0574, 0.5778],
         [0.1860, 0.7527, 0.4621]],

        [[0.1863, 0.4881, 0.7828],
         [0.4754, 0.0325, 0.9927],
         [0.2476, 0.0237, 0.2033],
         ...,
         [0.2839, 0.5492, 0.4335],
         [0.0179, 0.7043, 0.8447],
         [0.4572, 0.2412, 0.8079]],

        ...,

        [[0.3602, 0.0926, 0.1313],
         [0.6938, 0.6845, 0.6845],
         [0.3270, 0.0476, 0.8101],
         ...,
         [0.0122, 0.8008, 0.5228],
         [0.1818, 0.9455, 0.6102],
         [0.8983, 0.2898, 0.7376]],

        [[0.1646, 0.8747, 0.1163],
         [0.5962, 0.0165, 0.0947],
         [0.

In [ ]:
image.ndim

3

In [ ]:
image.shape

torch.Size([244, 244, 3])

In [ ]:
# Random tensor with shape (3, 244, 244)
tensor = torch.tensor([
    [
        [0, 120, 150],  # First row of pixel intensities
        [80, 180, 200],   # Second row
        [50, 70, 0]      # Third row
    ]
])

# Convert tensor to uint8 type
tensor = tensor.to(torch.uint8)

# Define transforms to convert tensor to PIL Image
tensor_to_image = transforms.ToPILImage()

# Convert tensor to image
image = tensor_to_image(tensor)

# Display the image
plt.imshow(image)
plt.axis('off')
plt.show()

In [ ]:
zeros = torch.zeros(size=(2,3,4))
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
ones = torch.ones(size=(2,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# Creating a tensor from 0 to 9 as floating-point numbers
zero_to_ten = torch.arange(start=0, end=10, step=1, dtype=torch.float32)

# Creating a tensor with the same shape as zero_to_ten but filled with random numbers
zero_to_tenten_rand = torch.rand_like(input=zero_to_ten)

# Creating a tensor filled with random numbers of size 10
ten_rand = torch.rand(10)

print(zero_to_ten)
print(zero_to_tenten_rand)
print(ten_rand)


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0.7709, 0.8783, 0.6831, 0.5718, 0.0355, 0.6782, 0.0307, 0.4418, 0.6560,
        0.1013])
tensor([0.2384, 0.2122, 0.4659, 0.0182, 0.7646, 0.3549, 0.2720, 0.7971, 0.5192,
        0.7264])


In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
#basic operation
tensor = torch.tensor([[[1,2,3],
                       [4,5,6]],
                       [[1,2,3],
                       [4,5,6]]
                       ])
tensor * 10
torch.multiply(tensor, 10)

tensor([[[10, 20, 30],
         [40, 50, 60]],

        [[10, 20, 30],
         [40, 50, 60]]])

In [ ]:
tensor + 10

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[11, 12, 13],
         [14, 15, 16]]])

In [ ]:
tensor - 10

tensor([[[-9, -8, -7],
         [-6, -5, -4]],

        [[-9, -8, -7],
         [-6, -5, -4]]])

In [ ]:
tensor / 10

tensor([[[0.1000, 0.2000, 0.3000],
         [0.4000, 0.5000, 0.6000]],

        [[0.1000, 0.2000, 0.3000],
         [0.4000, 0.5000, 0.6000]]])

In [ ]:
#To perform matrix multiplication, the last dimension of tensor1 should match the second-to-last dimension of tensor2 (1st column == 2nd rows)
#shape(no of square brackets, rows, columns)
# no of square brackets should same

batch_a = torch.randn(3, 2, 2)  # Batch of 3 matrices of size 2x2
batch_b = torch.randn(3, 2, 2)  # Batch of 3 matrices of size 2x2

# Batch matrix multiplication
result = torch.matmul(batch_a, batch_b)
result
batch_a.ndim

3

In [ ]:
tensor1 = [[[1,2,3], [4,5,6]]]
tensor2 = [[[1,2],[1,3], [1,4]]]

# Convert Python lists to PyTorch tensors
tensor1 = torch.tensor(tensor1)
tensor2 = torch.tensor(tensor2)

tensor1 @ tensor2

tensor([[[ 6, 20],
         [15, 47]]])

In [ ]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

Tensor agregation

In [ ]:
torch.min(x)

tensor(1)

In [ ]:
torch.max(x) , x.max()

(tensor(91), tensor(91))

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
#means work only on floating point or complex dtype
torch.mean(x.type(torch.float32))

tensor(46.)

In [ ]:
x.sum() , torch.sum(x)

(tensor(460), tensor(460))

In [ ]:
#return position

x.argmax()

tensor(9)

In [ ]:
#reshape tensor
x = torch.arange(1,13,1)
x.reshape(3,4)

z = x.view(3,4)
z[:,0]=5
x, z

(tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12]),
 tensor([[ 5,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 5, 10, 11, 12]]))

In [ ]:
# Create a tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape the tensor to a different shape it is similar to reshape but not permanently assign reshape tensor to memory
y = x.view(3, 2)

print(y)


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
#view(-1) will flatten the tensor x into a 1D tensor, with the size automatically inferred to accommodate all the elements

x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape the tensor with -1 to automatically infer size
y = x.view(-1)

print(y)

tensor([1, 2, 3, 4, 5, 6])


In [ ]:
# Create a tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Transpose the tensor
y = x.transpose(0, 1)

print(y)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
#Stacking along dimension 0 combines tensors along the batch dimension.
#Stacking along dimension 1 combines tensors along the feature or channel dimension.
#stacking -> combine multiple tensors
#vstack --> on top of each other dim=0
#hstack --> side by side dim=1
x = torch.arange(1,13,1)
stacked = torch.stack([x,x,x], dim=-1)
stacked

tensor([[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12]])

In [ ]:
#Squeezes input to remove all the dimenions with value 1
x = torch.randn(1, 3, 1, 4)
x
y = torch.squeeze(x)
y

tensor([[-1.1316, -0.1743,  0.4644, -1.3234],
        [-1.8652, -0.8235,  0.6533,  2.0771],
        [-0.7976,  1.0081,  0.8850, -0.1559]])

In [ ]:
#only the third dimension (index 2) is squeezed because it has a size of 1
x = torch.randn(1, 3, 1, 4)
y = torch.squeeze(x, dim=2)
y

tensor([[[ 0.5666,  0.0849,  1.8524, -0.0665],
         [-2.2076, -0.1963, -0.5524, -0.6595],
         [-1.3359,  0.2774,  0.7163,  1.3213]]])

In [ ]:
#dimensions 0 and 2 are squeezed, while dimension index 1 remains intact because it does not have size 1
x = torch.randn(1, 3, 1, 4)
y = torch.squeeze(x, dim=(0, 2))
print(y.shape)  # Output: (3, 4)


In [ ]:
#dimensions change (different view of the original tensor)
#swapped the dimension
#the dimensions of y are rearranged such that the original dimension 1 becomes dimension 0, the original dimension 2 becomes dimension 1, and the original dimension 0 becomes dimension 2.
x = torch.randn(2, 3, 4)
x
y = x.permute(1, 2, 0)
y[0][1][0]

tensor(-0.2036)

In [ ]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
print(f"previous shape: {x_permuted.shape}"), print(f"permuted shape: {x_permuted.shape}")

previous shape: torch.Size([3, 224, 224])
permuted shape: torch.Size([3, 224, 224])


(None, None)

In [ ]:
#Indexing
x = torch.tensor([
    [
      [1,2,3],
      [4,5,6],
      [7,8,9]
    ],
    [
      [1,2,3],
      [4,5,6],
      [6,7,8]
    ]
                  ])
x.shape

# 1st square, all, second
x[1,:,2]

#all, all, second
x[:,:, 2]

#9 0f 1st
x[0,2,2]

tensor(9)

In [ ]:
#reproducebility
#to reduce randomeness in neural network
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
x= torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
y= torch.rand(3,4)
print(x)
print(y)
print(x==y)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')